### ISSUE TITLE
Fix unit tests and configure CI build for project

### ISSUE THREAD

**Issue by Serg046** [verdie-g/Moq.DataReader#2]
There are two failed tests - TestGetNameEmpty and TestGetNameOutOfRange.
Could you please fix it?
Also I suggest to add the project to some CI system to detect failed tests after each commit.
For example AppVeyor works good for me.

**Comment by verdie-g** [comment]
There is lot to do on this library.

TestGetNameEmpty and TestGetNameOutOfRange fail because I couldn't make exceptions work ([this commented code doesn't work, I don't know why](https://github.com/verdie-g/Moq.DataReader/blob/master/Moq.DataReader/MockExtension.cs#L66)).

This library shouldn't mock DbDataReader but IDataReader because DbDataReader async functions are not virtual therefore they can't be mocked.

I'll try to fix that when I'll have some time.

**Comment by Serg046** [comment]
I fixed tests and added mocking for IDataReader.
Please take a look on this PR https://github.com/verdie-g/Moq.DataReader/pull/1
It also includes my previous change about possibility to pass IEnumerable/Array into setup method because PR had been created before the current issue was opened.

**Comment by verdie-g** [comment]
Thanks !

Can I replace DbDataReader with IDataReader or you found useful to mock methods like GetStream, VisibleFieldCount, ... ?

**Comment by Serg046** [comment]
Yeah, I also prefer to leave IDataReader only

**Comment by verdie-g** [comment]
I published the version 0.2.0.
